export const path = Object.freeze({
  home: "/",
  services: "/services",
  activeServices: "/active-services",
  blog: "/blog",
  videos: "/videos",
  login: "/auth/login",
  signup: "/auth/signup",
  verifyEmail: "/auth/verify",
  checkEmail: "/auth/check-email",
  forgotPassword: "/auth/forgot-password",
  resetPassword: "/auth/reset-password",
  dashboard: "/dashboard",
  changePassword: "/dashboard/change-password",
  interviewPreps: "/services/interview-preps",
  agents: "/services/agents",
  consultations: "/services/consultations",
  denial: "/services/denial",
  funding: "/services/funding",
  postRelocation: "/services/post-relocation",
  projectManagement: "/services/project-management",
  report: "/services/report",
  verifyDocuments: "/services/verify-documents",
  paymentCallback: "/payment/callback",
  paymentSuccess: "/payment/success",
  paymentFailed: "/payment/failed"
});
