import { log } from "console";

export const path = Object.freeze({
  home: "/",
  services: "/services",
  activeServices: "/active-services",
  blog: "/blog",
  videos: "/videos",
  about: "/about",
  contactUs: "/contact_us",
  login: "/auth/login",
  signup: "/auth/signup",
  interviewPreps: "/services/interview-preps",
  agents: "/services/agents",
  consultations: "/services/consultations",
  denial: "/services/denial",
  funding: "/services/funding",
  postRelocation: "/services/post-relocation",
  projectManagement: "/services/project-management",
  report: "/services/report",
  verifyDocuments: "/services/verify-documents",
  forAgents: "/discover/for-agents",
  forDiaspora: "/discover/for-diaspora",
  forHopefuls: "/discover/japa-hopefuls",
  privacyPolicy: "/legal/privacy-policy",
  termsOfService: "/legal/terms-of-service",
  acceptableUse: "/legal/acceptable-use-policy",
  infoSecurity: "/legal/information-security-policy",
});
