import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { ControllerProvider } from "@/providers/Controller";
import GlobalStyles from "@/components/GlobalStyles";
import "@/styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const monstserrat = Montserrat({
  variable: "--font-monstserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ControllerProvider>
      <html lang="en">
        <body
          className={`${inter.variable} ${monstserrat.variable} antialiased`}
        >
          <GlobalStyles />
          {children}
        </body>
      </html>
    </ControllerProvider>
  );
}
