import type { Metadata } from "next";
import { Inter, Roboto,Inria_Sans } from "next/font/google";
import "./globals.css";
import { ControllerProvider } from "@/providers/Controller";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
})

const inria = Inria_Sans({
  variable: "--font-inria",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ControllerProvider>
      <html lang="en">
        <body className={`${inter.variable} ${roboto.variable} ${inria.variable} antialiased`}>
          {children}
        </body>
      </html>
    </ControllerProvider>
  );
}
