// import Head from "next/head";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Features from "@/components/Landing/Features";
import Image from "next/image";
import { useEffect } from "react";

export default function Home() {

  useEffect(() => {
    console.log("Hello, world!")
  }, [])
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={"font-montserrat"}>
        <Header />
        <main className="flex w-full flex-col items-center gap-[50px] bg-white">
          <Hero
            title={
              <>
                Your Next Adventure{" "}
                <span className="font-bold text-primary-on_primary_fixed">
                  Starts Here!
                </span>
              </>
            }
            desc="Expert travel planning tailored to your dreams. Let us handle the details while you explore the world effortlessly."
          />
          <Features />
        </main>
      </div>
    </>
  );
}
