import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import DontFallForScam from "@/components/Landing/DontFallForScam";
import FAQs from "@/components/Landing/FAQs";
import Features from "@/components/Landing/Features";
import KeyPoints from "@/components/Landing/KeyPoints";
import MissionStatement from "@/components/Landing/MissionStatement";
import Services from "@/components/Landing/Services";
import Testimonial from "@/components/Landing/Testimonial";
import { faqData } from "@/libs/constants";
import HeroBG from "@/img/defaultHeroBG.svg?url";
import {useController} from "@/hooks/useController";


export default function Home() {
  const { isHeroInView } = useController();
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div
        className={
          "flex w-full flex-col items-center gap-[50px] bg-white overflow-hidden"
        }
      >
        <Header isHeroInView={isHeroInView} />
        <main className="flex w-full flex-col items-center gap-[50px]">
          <Hero
            title={
              <>
                Your Next Adventure{" "}
                <span className="font-bold text-primary-on_primary_fixed">
                  Starts Here!
                </span>
              </>
            }
            desc="Expert travel planning tailored to your dreams. Let us handle the details while you explore the world effortlessly."
            heroImage={HeroBG}
          />
          <Features />
          <KeyPoints />
          <MissionStatement />
          <Services />
          <DontFallForScam />
          <Testimonial />
          <FAQs faqData={faqData} />
        </main>
        <Footer />
      </div>
    </>
  );
}
